"""factor total is not a score

Revision ID: 06f4b2229e77
Revises: 935a7404a195
Create Date: 2026-09-01 13:41:03.918058
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '06f4b2229e77'
down_revision: str | None = '935a7404a195'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_analytics', sa.Column('factor_total', sa.Numeric(precision=8, scale=6), nullable=True))
    op.drop_column('user_analytics', 'weighted_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_analytics', sa.Column('weighted_score', sa.NUMERIC(precision=8, scale=6), autoincrement=False, nullable=True))
    op.drop_column('user_analytics', 'factor_total')
    # ### end Alembic commands ###
