"""quote comparison module

Revision ID: 08c8801ff79d
Revises: 751ffb798f7e
Create Date: 2026-08-31 15:00:31.556849
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '08c8801ff79d'
down_revision: str | None = '751ffb798f7e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quote_comparisons',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('analysed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quote_comparisons_created_by_id'), 'quote_comparisons', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_quote_comparisons_status'), 'quote_comparisons', ['status'], unique=False)
    op.create_table('supplier_quotes',
    sa.Column('comparison_id', sa.UUID(), nullable=False),
    sa.Column('supplier_name', sa.String(length=200), nullable=False),
    sa.Column('quote_number', sa.String(length=100), nullable=True),
    sa.Column('quote_date', sa.String(length=40), nullable=True),
    sa.Column('validity', sa.String(length=120), nullable=True),
    sa.Column('delivery_time', sa.String(length=120), nullable=True),
    sa.Column('payment_terms', sa.String(length=200), nullable=True),
    sa.Column('warranty', sa.String(length=200), nullable=True),
    sa.Column('incoterms', sa.String(length=60), nullable=True),
    sa.Column('contact', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('fx_rate', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('quoted_total', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('discount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('freight', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('tax', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_type', sa.String(length=100), nullable=True),
    sa.Column('file_bytes', sa.LargeBinary(), nullable=True),
    sa.Column('extraction_note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['comparison_id'], ['quote_comparisons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_supplier_quotes_comparison', 'supplier_quotes', ['comparison_id'], unique=False)
    op.create_table('supplier_quote_items',
    sa.Column('quote_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('part_number', sa.String(length=120), nullable=True),
    sa.Column('brand', sa.String(length=120), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('lead_time', sa.String(length=120), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity >= 0', name='ck_quote_item_quantity_positive'),
    sa.ForeignKeyConstraint(['quote_id'], ['supplier_quotes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_supplier_quote_items_quote', 'supplier_quote_items', ['quote_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_supplier_quote_items_quote', table_name='supplier_quote_items')
    op.drop_table('supplier_quote_items')
    op.drop_index('ix_supplier_quotes_comparison', table_name='supplier_quotes')
    op.drop_table('supplier_quotes')
    op.drop_index(op.f('ix_quote_comparisons_status'), table_name='quote_comparisons')
    op.drop_index(op.f('ix_quote_comparisons_created_by_id'), table_name='quote_comparisons')
    op.drop_table('quote_comparisons')
    # ### end Alembic commands ###
