"""user analytics runs

Revision ID: 261b995f8673
Revises: 54113b331a9d
Create Date: 2026-09-01 11:09:11.464221
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '261b995f8673'
down_revision: str | None = '54113b331a9d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_runs',
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('team_name', sa.String(length=160), nullable=True),
    sa.Column('policy_id', sa.UUID(), nullable=True),
    sa.Column('policy_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.Column('rows_read', sa.Integer(), nullable=False),
    sa.Column('excluded_note', sa.Text(), nullable=True),
    sa.Column('saved', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['policy_id'], ['assignment_policies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_analytics_runs_team_created', 'analytics_runs', ['team_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_analytics_runs_team_id'), 'analytics_runs', ['team_id'], unique=False)
    op.create_table('user_analytics',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('sharepoint_lookup_id', sa.String(length=40), nullable=True),
    sa.Column('total_tasks', sa.Integer(), nullable=False),
    sa.Column('open_tasks', sa.Integer(), nullable=False),
    sa.Column('completed_tasks', sa.Integer(), nullable=False),
    sa.Column('overdue_tasks', sa.Integer(), nullable=False),
    sa.Column('due_soon_tasks', sa.Integer(), nullable=False),
    sa.Column('no_status_tasks', sa.Integer(), nullable=False),
    sa.Column('last_assigned_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('days_since_last_assign', sa.Integer(), nullable=True),
    sa.Column('labels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('capacity', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('effective_load', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('max_open', sa.Integer(), nullable=True),
    sa.Column('excluded', sa.Boolean(), nullable=False),
    sa.Column('excluded_reason', sa.Text(), nullable=True),
    sa.Column('priority_score', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('factors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['analytics_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_analytics_run_rank', 'user_analytics', ['run_id', 'rank'], unique=False)
    op.create_index('ix_user_analytics_user', 'user_analytics', ['user_id'], unique=False)
    op.drop_index(op.f('uq_assignment_policy_org_default'), table_name='assignment_policies', postgresql_where='(team_id IS NULL)')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('uq_assignment_policy_org_default'), 'assignment_policies', ['team_id'], unique=True, postgresql_where='(team_id IS NULL)')
    op.drop_index('ix_user_analytics_user', table_name='user_analytics')
    op.drop_index('ix_user_analytics_run_rank', table_name='user_analytics')
    op.drop_table('user_analytics')
    op.drop_index(op.f('ix_analytics_runs_team_id'), table_name='analytics_runs')
    op.drop_index('ix_analytics_runs_team_created', table_name='analytics_runs')
    op.drop_table('analytics_runs')
    # ### end Alembic commands ###
