"""managers are not given work

Revision ID: 2b415ac9c166
Revises: a2f8a2c6fba7
Create Date: 2026-09-01 11:14:57.243547
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '2b415ac9c166'
down_revision: str | None = 'a2f8a2c6fba7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment_policies', sa.Column('excluded_roles', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('\'["manager", "team_manager"]\'::jsonb'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignment_policies', 'excluded_roles')
    # ### end Alembic commands ###
