"""user labels and assignment policy

Revision ID: 54113b331a9d
Revises: 08c8801ff79d
Create Date: 2026-08-31 17:45:30.295413
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '54113b331a9d'
down_revision: str | None = '08c8801ff79d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignment_policies',
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('default_capacity', sa.Numeric(precision=6, scale=3), server_default=sa.text('1.0'), nullable=False),
    sa.Column('capacity_by_label', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('default_max_open', sa.Integer(), nullable=True),
    sa.Column('max_open_by_label', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('excluded_labels', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('exclude_on_leave', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('new_joiner_days', sa.Integer(), server_default=sa.text('90'), nullable=False),
    sa.Column('weight_load', sa.Numeric(precision=4, scale=3), server_default=sa.text('0.45'), nullable=False),
    sa.Column('weight_open_count', sa.Numeric(precision=4, scale=3), server_default=sa.text('0.30'), nullable=False),
    sa.Column('weight_idle_days', sa.Numeric(precision=4, scale=3), server_default=sa.text('0.25'), nullable=False),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('new_joiner_days >= 0', name='ck_assignment_new_joiner_days'),
    sa.CheckConstraint('weight_load >= 0 AND weight_open_count >= 0 AND weight_idle_days >= 0', name='ck_assignment_weights_non_negative'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', name='uq_assignment_policy_team')
    )
    op.create_index(op.f('ix_assignment_policies_team_id'), 'assignment_policies', ['team_id'], unique=False)
    op.create_table('labels',
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'key', name='uq_labels_team_key')
    )
    op.create_index(op.f('ix_labels_key'), 'labels', ['key'], unique=False)
    op.create_index(op.f('ix_labels_kind'), 'labels', ['kind'], unique=False)
    op.create_index(op.f('ix_labels_team_id'), 'labels', ['team_id'], unique=False)
    op.create_table('label_assignments',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('label_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('assigned_by_id', sa.UUID(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['label_id'], ['labels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'label_id', 'team_id', name='uq_label_assignment')
    )
    op.create_index(op.f('ix_label_assignments_label_id'), 'label_assignments', ['label_id'], unique=False)
    op.create_index(op.f('ix_label_assignments_team_id'), 'label_assignments', ['team_id'], unique=False)
    op.create_index(op.f('ix_label_assignments_user_id'), 'label_assignments', ['user_id'], unique=False)
    op.add_column('users', sa.Column('joined_on', sa.Date(), nullable=True))
    # Postgres treats NULLs as distinct in a unique constraint, so
    # uq_assignment_policy_team does not stop a second org-wide default being
    # created. This does. Without it, which default applies would be a race.
    op.create_index(
        'uq_assignment_policy_org_default',
        'assignment_policies',
        ['team_id'],
        unique=True,
        postgresql_where=sa.text('team_id IS NULL'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_assignment_policy_org_default', table_name='assignment_policies')
    op.drop_column('users', 'joined_on')
    op.drop_index(op.f('ix_label_assignments_user_id'), table_name='label_assignments')
    op.drop_index(op.f('ix_label_assignments_team_id'), table_name='label_assignments')
    op.drop_index(op.f('ix_label_assignments_label_id'), table_name='label_assignments')
    op.drop_table('label_assignments')
    op.drop_index(op.f('ix_labels_team_id'), table_name='labels')
    op.drop_index(op.f('ix_labels_kind'), table_name='labels')
    op.drop_index(op.f('ix_labels_key'), table_name='labels')
    op.drop_table('labels')
    op.drop_index(op.f('ix_assignment_policies_team_id'), table_name='assignment_policies')
    op.drop_table('assignment_policies')
    # ### end Alembic commands ###
