"""priority score is an ordinal from 1

Revision ID: 55aa8cd0488d
Revises: 2b415ac9c166
Create Date: 2026-09-01 11:23:16.725682
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '55aa8cd0488d'
down_revision: str | None = '2b415ac9c166'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_analytics', sa.Column('weighted_score', sa.Numeric(precision=8, scale=6), nullable=True))
    op.alter_column('user_analytics', 'priority_score',
               existing_type=sa.NUMERIC(precision=8, scale=6),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_index(op.f('ix_user_analytics_run_rank'), table_name='user_analytics')
    op.create_index('ix_user_analytics_run_priority', 'user_analytics', ['run_id', 'priority_score'], unique=False)
    op.drop_column('user_analytics', 'rank')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_analytics', sa.Column('rank', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index('ix_user_analytics_run_priority', table_name='user_analytics')
    op.create_index(op.f('ix_user_analytics_run_rank'), 'user_analytics', ['run_id', 'rank'], unique=False)
    op.alter_column('user_analytics', 'priority_score',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=8, scale=6),
               existing_nullable=True)
    op.drop_column('user_analytics', 'weighted_score')
    # ### end Alembic commands ###
