"""team dashboards and team scoped pages

Revision ID: 5cfb1b4b304d
Revises: aaf129cafe20
Create Date: 2026-08-25 16:05:07.476209
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '5cfb1b4b304d'
down_revision: str | None = 'aaf129cafe20'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_dashboard_widgets',
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('widget_key', sa.String(length=40), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('configured_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['configured_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'widget_key', name='uq_team_dashboard_widget')
    )
    op.create_index(op.f('ix_team_dashboard_widgets_team_id'), 'team_dashboard_widgets', ['team_id'], unique=False)
    op.add_column('module_pages', sa.Column('team_scoped', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('module_pages', 'team_scoped')
    op.drop_index(op.f('ix_team_dashboard_widgets_team_id'), table_name='team_dashboard_widgets')
    op.drop_table('team_dashboard_widgets')
    # ### end Alembic commands ###
