"""active and bid closed counts

Revision ID: 935a7404a195
Revises: a9740549167d
Create Date: 2026-09-01 13:32:33.644287
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '935a7404a195'
down_revision: str | None = 'a9740549167d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_analytics', sa.Column('bid_closed_tasks', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('user_analytics', sa.Column('active_tasks', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_analytics', 'active_tasks')
    op.drop_column('user_analytics', 'bid_closed_tasks')
    # ### end Alembic commands ###
