"""new joiner fallback is opt in

Revision ID: a2f8a2c6fba7
Revises: 261b995f8673
Create Date: 2026-09-01 11:11:17.613360
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'a2f8a2c6fba7'
down_revision: str | None = '261b995f8673'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment_policies', sa.Column('new_joiner_from_first_seen', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignment_policies', 'new_joiner_from_first_seen')
    # ### end Alembic commands ###
