"""expired task count

Revision ID: a9740549167d
Revises: 55aa8cd0488d
Create Date: 2026-09-01 13:26:55.454765
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'a9740549167d'
down_revision: str | None = '55aa8cd0488d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_analytics', sa.Column('expired_tasks', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_analytics', 'expired_tasks')
    # ### end Alembic commands ###
