"""quote requests and approval

Revision ID: a9b4efac2de1
Revises: 06f4b2229e77
Create Date: 2026-09-01 14:16:52.232153
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'a9b4efac2de1'
down_revision: str | None = '06f4b2229e77'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quote_requests',
    sa.Column('reference', sa.String(length=60), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('customer_name', sa.String(length=200), nullable=False),
    sa.Column('customer_id', sa.String(length=60), nullable=True),
    sa.Column('contact_person', sa.String(length=200), nullable=True),
    sa.Column('reference_number', sa.String(length=120), nullable=True),
    sa.Column('quote_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('salesperson_name', sa.String(length=200), nullable=True),
    sa.Column('place_of_supply', sa.String(length=120), nullable=True),
    sa.Column('payment_terms', sa.String(length=200), nullable=True),
    sa.Column('delivery_terms', sa.String(length=200), nullable=True),
    sa.Column('cf_bcd', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cf_portal', sa.String(length=120), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('terms', sa.Text(), nullable=True),
    sa.Column('discount', sa.Numeric(precision=18, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('shipping_charge', sa.Numeric(precision=18, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('adjustment', sa.Numeric(precision=18, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('multiple_supplier_quotes', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('comparison_id', sa.UUID(), nullable=True),
    sa.Column('selected_supplier_quote_id', sa.UUID(), nullable=True),
    sa.Column('win_probability', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('win_basis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('assigned_to_id', sa.UUID(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revision', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('discount >= 0', name='ck_quote_request_discount'),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['comparison_id'], ['quote_comparisons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['selected_supplier_quote_id'], ['supplier_quotes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quote_requests_assigned_to_id'), 'quote_requests', ['assigned_to_id'], unique=False)
    op.create_index(op.f('ix_quote_requests_created_by_id'), 'quote_requests', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_quote_requests_reference'), 'quote_requests', ['reference'], unique=False)
    op.create_index(op.f('ix_quote_requests_status'), 'quote_requests', ['status'], unique=False)
    op.create_index('ix_quote_requests_team_status', 'quote_requests', ['team_id', 'status'], unique=False)
    op.create_table('quote_comments',
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('target_ref', sa.String(length=120), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['request_id'], ['quote_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quote_comments_request_target', 'quote_comments', ['request_id', 'target_type'], unique=False)
    op.create_table('quote_request_items',
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('item_code', sa.String(length=120), nullable=True),
    sa.Column('brand', sa.String(length=120), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('discount', sa.Numeric(precision=18, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('tax_name', sa.String(length=60), nullable=True),
    sa.Column('tax_percentage', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('cost_rate', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('source_supplier_quote_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity >= 0', name='ck_quote_item_quantity'),
    sa.ForeignKeyConstraint(['request_id'], ['quote_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_supplier_quote_id'], ['supplier_quotes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quote_request_items_request', 'quote_request_items', ['request_id'], unique=False)
    op.create_table('quote_reviews',
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('selected_supplier_quote_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['quote_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['selected_supplier_quote_id'], ['supplier_quotes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quote_reviews_request', 'quote_reviews', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_quote_reviews_request', table_name='quote_reviews')
    op.drop_table('quote_reviews')
    op.drop_index('ix_quote_request_items_request', table_name='quote_request_items')
    op.drop_table('quote_request_items')
    op.drop_index('ix_quote_comments_request_target', table_name='quote_comments')
    op.drop_table('quote_comments')
    op.drop_index('ix_quote_requests_team_status', table_name='quote_requests')
    op.drop_index(op.f('ix_quote_requests_status'), table_name='quote_requests')
    op.drop_index(op.f('ix_quote_requests_reference'), table_name='quote_requests')
    op.drop_index(op.f('ix_quote_requests_created_by_id'), table_name='quote_requests')
    op.drop_index(op.f('ix_quote_requests_assigned_to_id'), table_name='quote_requests')
    op.drop_table('quote_requests')
    # ### end Alembic commands ###
