"""module visibility per team

Revision ID: aaf129cafe20
Revises: b16422642e51
Create Date: 2026-08-25 15:49:10.834369
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'aaf129cafe20'
down_revision: str | None = 'b16422642e51'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modules',
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('admin_only', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('module_pages',
    sa.Column('module_key', sa.String(length=40), nullable=False),
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('path', sa.String(length=200), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['module_key'], ['modules.key'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module_key', 'key', name='uq_module_page_key')
    )
    op.create_index(op.f('ix_module_pages_module_key'), 'module_pages', ['module_key'], unique=False)
    op.create_table('team_module_access',
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('module_key', sa.String(length=40), nullable=False),
    sa.Column('all_pages', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('granted_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['granted_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['module_key'], ['modules.key'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'module_key', name='uq_team_module')
    )
    op.create_index(op.f('ix_team_module_access_module_key'), 'team_module_access', ['module_key'], unique=False)
    op.create_index(op.f('ix_team_module_access_team_id'), 'team_module_access', ['team_id'], unique=False)
    op.create_table('team_page_access',
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('page_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['module_pages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'page_id', name='uq_team_page')
    )
    op.create_index(op.f('ix_team_page_access_page_id'), 'team_page_access', ['page_id'], unique=False)
    op.create_index(op.f('ix_team_page_access_team_id'), 'team_page_access', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_page_access_team_id'), table_name='team_page_access')
    op.drop_index(op.f('ix_team_page_access_page_id'), table_name='team_page_access')
    op.drop_table('team_page_access')
    op.drop_index(op.f('ix_team_module_access_team_id'), table_name='team_module_access')
    op.drop_index(op.f('ix_team_module_access_module_key'), table_name='team_module_access')
    op.drop_table('team_module_access')
    op.drop_index(op.f('ix_module_pages_module_key'), table_name='module_pages')
    op.drop_table('module_pages')
    op.drop_table('modules')
    # ### end Alembic commands ###
