"""hr module: openings, applications, employee documents, performance reviews

Revision ID: c7d1a4b90e33
Revises: e81c5d3f6a72
Create Date: 2026-09-05

Written by hand rather than autogenerated, so the ``RESTRICT`` on the two
template foreign keys is deliberate and stays that way: deleting a form that
applications or reviews were answered against would leave those answers
unreadable, and the database should refuse rather than let it happen quietly.
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "c7d1a4b90e33"
down_revision: str | None = "e81c5d3f6a72"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ── job openings ───────────────────────────────────────────────────
    op.create_table(
        "job_openings",
        sa.Column("id", postgresql.UUID(as_uuid=True),
                  server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("reference", sa.String(length=64), nullable=True),
        sa.Column("team_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("department", sa.String(length=120), nullable=True),
        sa.Column("location", sa.String(length=160), nullable=True),
        sa.Column("employment_type", sa.String(length=20), nullable=False),
        sa.Column("headcount", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("salary_range", sa.String(length=120), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("requirements", sa.Text(), nullable=True),
        sa.Column("template_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("template_version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("public_token", sa.String(length=64), nullable=False),
        sa.Column("publicly_listed", sa.Boolean(), server_default=sa.text("false"),
                  nullable=False),
        sa.Column("hosted_form", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closes_on", sa.Date(), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("updated_by_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
                  nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
                  nullable=False),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ondelete="SET NULL"),
        # RESTRICT: see the module docstring.
        sa.ForeignKeyConstraint(["template_id"], ["form_templates.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["updated_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_job_openings_slug"), "job_openings", ["slug"], unique=True)
    # Unique, and indexed for the public lookup: every candidate request is a
    # single-row read on this column.
    op.create_index(
        op.f("ix_job_openings_public_token"), "job_openings", ["public_token"], unique=True
    )
    op.create_index(op.f("ix_job_openings_status"), "job_openings", ["status"])
    op.create_index(op.f("ix_job_openings_team_id"), "job_openings", ["team_id"])
    op.create_index(
        "ix_job_openings_status_posted", "job_openings", ["status", "posted_at"]
    )

    # ── applications ───────────────────────────────────────────────────
    op.create_table(
        "job_applications",
        sa.Column("id", postgresql.UUID(as_uuid=True),
                  server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("opening_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("candidate_name", sa.String(length=200), nullable=False),
        sa.Column("candidate_email", sa.String(length=320), nullable=False),
        sa.Column("candidate_phone", sa.String(length=40), nullable=True),
        sa.Column("answers", postgresql.JSONB(astext_type=sa.Text()),
                  server_default=sa.text("'{}'::jsonb"), nullable=False),
        sa.Column("template_version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("score", postgresql.JSONB(astext_type=sa.Text()),
                  server_default=sa.text("'{}'::jsonb"), nullable=False),
        sa.Column("score_percent", sa.Numeric(precision=5, scale=1), nullable=True),
        sa.Column("stage", sa.String(length=16), nullable=False),
        sa.Column("stage_note", sa.Text(), nullable=True),
        sa.Column("internal_notes", sa.Text(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
                  nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decided_by_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("hired_user_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
                  nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
                  nullable=False),
        sa.ForeignKeyConstraint(["opening_id"], ["job_openings.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["decided_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["hired_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("opening_id", "candidate_email",
                            name="uq_application_opening_email"),
    )
    op.create_index(
        op.f("ix_job_applications_candidate_email"), "job_applications", ["candidate_email"]
    )
    op.create_index(op.f("ix_job_applications_stage"), "job_applications", ["stage"])
    op.create_index(
        "ix_job_applications_opening_stage", "job_applications", ["opening_id", "stage"]
    )

    op.create_table(
        "application_files",
        sa.Column("id", postgresql.UUID(as_uuid=True),
                  server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("application_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("field_key", sa.String(length=64), nullable=True),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=True),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("file_bytes", sa.LargeBinary(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
                  nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
                  nullable=False),
        sa.ForeignKeyConstraint(["application_id"], ["job_applications.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_application_files_application_id"), "application_files", ["application_id"]
    )

    # ── employee documents ─────────────────────────────────────────────
    op.create_table(
        "employee_documents",
        sa.Column("id", postgresql.UUID(as_uuid=True),
                  server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=True),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("file_bytes", sa.LargeBinary(), nullable=False),
        sa.Column("issued_on", sa.Date(), nullable=True),
        sa.Column("expires_on", sa.Date(), nullable=True),
        sa.Column("visible_to_employee", sa.Boolean(), server_default=sa.text("true"),
                  nullable=False),
        sa.Column("uploaded_by_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("source_application_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
                  nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
                  nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["uploaded_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["source_application_id"], ["job_applications.id"],
                                ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_employee_documents_user_id"), "employee_documents", ["user_id"])
    # Indexed so "what expires in the next 60 days" is a range scan rather than
    # a sweep of every personnel file.
    op.create_index(
        op.f("ix_employee_documents_expires_on"), "employee_documents", ["expires_on"]
    )
    op.create_index(
        "ix_employee_documents_user_kind", "employee_documents", ["user_id", "kind"]
    )

    # ── review cycles ──────────────────────────────────────────────────
    op.create_table(
        "review_cycles",
        sa.Column("id", postgresql.UUID(as_uuid=True),
                  server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("template_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("template_version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=True),
        sa.Column("period_end", sa.Date(), nullable=True),
        sa.Column("due_on", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("shared_with_subjects", sa.Boolean(), server_default=sa.text("false"),
                  nullable=False),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
                  nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
                  nullable=False),
        sa.ForeignKeyConstraint(["template_id"], ["form_templates.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_review_cycles_status"), "review_cycles", ["status"])

    op.create_table(
        "performance_reviews",
        sa.Column("id", postgresql.UUID(as_uuid=True),
                  server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("cycle_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("subject_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("reviewer_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("relation", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("answers", postgresql.JSONB(astext_type=sa.Text()),
                  server_default=sa.text("'{}'::jsonb"), nullable=False),
        sa.Column("score", postgresql.JSONB(astext_type=sa.Text()),
                  server_default=sa.text("'{}'::jsonb"), nullable=False),
        sa.Column("score_percent", sa.Numeric(precision=5, scale=1), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("declined_reason", sa.Text(), nullable=True),
        sa.Column("due_on", sa.Date(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
                  nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
                  nullable=False),
        sa.ForeignKeyConstraint(["cycle_id"], ["review_cycles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["subject_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["reviewer_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cycle_id", "subject_id", "reviewer_id",
                            name="uq_review_cycle_subject_reviewer"),
    )
    op.create_index(op.f("ix_performance_reviews_status"), "performance_reviews", ["status"])
    op.create_index(
        "ix_performance_reviews_reviewer_status", "performance_reviews",
        ["reviewer_id", "status"],
    )
    op.create_index(
        "ix_performance_reviews_subject", "performance_reviews", ["subject_id"]
    )


def downgrade() -> None:
    # Dropped in dependency order. Everything here is HR data — a downgrade
    # destroys offer letters, applications and reviews, which is worth knowing
    # before running it.
    op.drop_table("performance_reviews")
    op.drop_table("review_cycles")
    op.drop_table("employee_documents")
    op.drop_table("application_files")
    op.drop_table("job_applications")
    op.drop_table("job_openings")
