"""leave requests and settings

Revision ID: f46214f6fc92
Revises: 5cfb1b4b304d
Create Date: 2026-08-25 17:40:45.755227
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'f46214f6fc92'
down_revision: str | None = '5cfb1b4b304d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leave_requests',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('leave_type', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('decided_by', sa.String(length=20), nullable=True),
    sa.Column('decided_by_id', sa.UUID(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('emergency_override', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('conflicting_count', sa.Integer(), nullable=True),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notify_error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_date >= start_date', name='ck_leave_dates_ordered'),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_leave_range', 'leave_requests', ['start_date', 'end_date', 'status'], unique=False)
    op.create_index(op.f('ix_leave_requests_status'), 'leave_requests', ['status'], unique=False)
    op.create_index(op.f('ix_leave_requests_user_id'), 'leave_requests', ['user_id'], unique=False)
    op.create_table('leave_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('max_concurrent', sa.Integer(), server_default=sa.text('2'), nullable=False),
    sa.Column('auto_decide', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('limit_scope', sa.String(length=20), server_default=sa.text("'organisation'"), nullable=False),
    sa.Column('hr_team_slug', sa.String(length=64), server_default=sa.text("'hr'"), nullable=False),
    sa.Column('notify_hr_by_email', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('max_days_per_request', sa.Integer(), server_default=sa.text('30'), nullable=False),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leave_settings')
    op.drop_index(op.f('ix_leave_requests_user_id'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_status'), table_name='leave_requests')
    op.drop_index('ix_leave_range', table_name='leave_requests')
    op.drop_table('leave_requests')
    # ### end Alembic commands ###
