"""initial schema

Revision ID: d93542bdd988
Revises: 
Create Date: 2026-08-24 01:01:16.308677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd93542bdd988'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connector_status',
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('mode', sa.String(length=24), nullable=False),
    sa.Column('healthy', sa.Boolean(), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_error_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('cursor', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('name', name=op.f('pk_connector_status'))
    )
    op.create_table('job_runs',
    sa.Column('task_name', sa.String(length=120), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=True),
    sa.Column('args', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_runs'))
    )
    op.create_index(op.f('ix_job_runs_correlation_id'), 'job_runs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_job_runs_status'), 'job_runs', ['status'], unique=False)
    op.create_index(op.f('ix_job_runs_task_id'), 'job_runs', ['task_id'], unique=True)
    op.create_index(op.f('ix_job_runs_task_name'), 'job_runs', ['task_name'], unique=False)
    op.create_index('ix_job_runs_task_started', 'job_runs', ['task_name', 'started_at'], unique=False)
    op.create_table('permissions',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('module', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_permissions'))
    )
    op.create_index(op.f('ix_permissions_module'), 'permissions', ['module'], unique=False)
    op.create_table('users',
    sa.Column('azure_object_id', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_azure_object_id'), 'users', ['azure_object_id'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_table('email_outbox',
    sa.Column('to_addresses', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cc_addresses', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('sent_by', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['sent_by'], ['users.id'], name=op.f('fk_email_outbox_sent_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_outbox'))
    )
    op.create_index(op.f('ix_email_outbox_correlation_id'), 'email_outbox', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_email_outbox_status'), 'email_outbox', ['status'], unique=False)
    op.create_table('feature_flags',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_feature_flags_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_feature_flags'))
    )
    op.create_table('leave_balances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('allowance_days', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('taken_days', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_leave_balances_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leave_balances')),
    sa.UniqueConstraint('user_id', 'year', 'type', name='uq_leave_balances')
    )
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=60), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('urgency', sa.String(length=16), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=True),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('routed_by_rule_id', sa.UUID(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_user_read', 'notifications', ['user_id', 'read_at'], unique=False)
    op.create_table('teams',
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('lead_user_id', sa.UUID(), nullable=True),
    sa.Column('enabled_modules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_user_id'], ['users.id'], name=op.f('fk_teams_lead_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams'))
    )
    op.create_index(op.f('ix_teams_slug'), 'teams', ['slug'], unique=True)
    op.create_table('assignment_policies',
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('eligibility', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('capacity', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('distribution', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tie_break', sa.String(length=32), nullable=False),
    sa.Column('fallback', sa.String(length=32), nullable=False),
    sa.Column('allow_manual_override', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('published_by', sa.UUID(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['published_by'], ['users.id'], name=op.f('fk_assignment_policies_published_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_assignment_policies_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assignment_policies')),
    sa.UniqueConstraint('team_id', 'name', name='uq_assignment_policies_team_name')
    )
    op.create_index('ix_assignment_policies_team_active', 'assignment_policies', ['team_id', 'active'], unique=False)
    op.create_table('audit_log',
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_log_actor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_audit_log_team_id_teams'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index('ix_audit_log_actor_created', 'audit_log', ['actor_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_actor_id'), 'audit_log', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_log_correlation_id'), 'audit_log', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_index('ix_audit_log_entity', 'audit_log', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_log_team_id'), 'audit_log', ['team_id'], unique=False)
    op.create_table('holidays',
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_holidays_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_holidays')),
    sa.UniqueConstraint('team_id', 'title', 'start_date', name='uq_holidays_team_title_start')
    )
    op.create_index(op.f('ix_holidays_start_date'), 'holidays', ['start_date'], unique=False)
    op.create_table('labels',
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_labels_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_labels')),
    sa.UniqueConstraint('team_id', 'key', name='uq_labels_team_id_key')
    )
    op.create_index(op.f('ix_labels_key'), 'labels', ['key'], unique=False)
    op.create_index(op.f('ix_labels_kind'), 'labels', ['kind'], unique=False)
    op.create_table('leave_requests',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('days', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('approver_id', sa.UUID(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('handoff_to', sa.UUID(), nullable=True),
    sa.Column('handoff_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('routed_by_rule_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], name=op.f('fk_leave_requests_approver_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['handoff_to'], ['users.id'], name=op.f('fk_leave_requests_handoff_to_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_leave_requests_team_id_teams'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_leave_requests_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leave_requests'))
    )
    op.create_index(op.f('ix_leave_requests_status'), 'leave_requests', ['status'], unique=False)
    op.create_index('ix_leave_requests_team_dates', 'leave_requests', ['team_id', 'start_date', 'end_date'], unique=False)
    op.create_index(op.f('ix_leave_requests_team_id'), 'leave_requests', ['team_id'], unique=False)
    op.create_index(op.f('ix_leave_requests_user_id'), 'leave_requests', ['user_id'], unique=False)
    op.create_index('ix_leave_requests_user_status', 'leave_requests', ['user_id', 'status'], unique=False)
    op.create_table('leave_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_leave_settings_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leave_settings')),
    sa.UniqueConstraint('team_id', 'key', name='uq_leave_settings_team_key')
    )
    op.create_table('proposals',
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('external_ref', sa.String(length=120), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('customer_name', sa.String(length=300), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('submission_status', sa.String(length=60), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('previous_owner', sa.UUID(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bcd', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('priority_score', sa.Integer(), nullable=False),
    sa.Column('required_labels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.String(length=120), nullable=True),
    sa.Column('source_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], name=op.f('fk_proposals_assigned_to_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['previous_owner'], ['users.id'], name=op.f('fk_proposals_previous_owner_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_proposals_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_proposals')),
    sa.UniqueConstraint('source', 'source_id', name='uq_proposals_source_source_id')
    )
    op.create_index('ix_proposals_assigned_status', 'proposals', ['assigned_to', 'status'], unique=False)
    op.create_index(op.f('ix_proposals_assigned_to'), 'proposals', ['assigned_to'], unique=False)
    op.create_index('ix_proposals_bcd', 'proposals', ['bcd'], unique=False)
    op.create_index(op.f('ix_proposals_external_ref'), 'proposals', ['external_ref'], unique=False)
    op.create_index(op.f('ix_proposals_status'), 'proposals', ['status'], unique=False)
    op.create_index(op.f('ix_proposals_team_id'), 'proposals', ['team_id'], unique=False)
    op.create_index('ix_proposals_team_status', 'proposals', ['team_id', 'status'], unique=False)
    op.create_table('roles',
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_team_scoped', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_roles_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('team_id', 'key', name='uq_roles_team_id_key')
    )
    op.create_index('ix_roles_key', 'roles', ['key'], unique=False)
    op.create_table('rule_sets',
    sa.Column('decision_point', sa.String(length=60), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('evaluate_all', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('published_by', sa.UUID(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['published_by'], ['users.id'], name=op.f('fk_rule_sets_published_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_rule_sets_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rule_sets')),
    sa.UniqueConstraint('decision_point', 'team_id', 'name', name='uq_rule_sets_dp_team_name')
    )
    op.create_index('ix_rule_sets_dp_team', 'rule_sets', ['decision_point', 'team_id'], unique=False)
    op.create_table('assignment_policy_versions',
    sa.Column('policy_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_assignment_policy_versions_author_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['policy_id'], ['assignment_policies.id'], name=op.f('fk_assignment_policy_versions_policy_id_assignment_policies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assignment_policy_versions')),
    sa.UniqueConstraint('policy_id', 'version', name='uq_assignment_policy_versions')
    )
    op.create_table('label_assignments',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('label_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('assigned_by', sa.UUID(), nullable=True),
    sa.Column('granted_by_rule_id', sa.UUID(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], name=op.f('fk_label_assignments_assigned_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['label_id'], ['labels.id'], name=op.f('fk_label_assignments_label_id_labels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_label_assignments_team_id_teams'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_label_assignments_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_label_assignments')),
    sa.UniqueConstraint('user_id', 'label_id', 'team_id', name='uq_label_assignments_user_id_label_id_team_id')
    )
    op.create_index(op.f('ix_label_assignments_label_id'), 'label_assignments', ['label_id'], unique=False)
    op.create_index(op.f('ix_label_assignments_user_id'), 'label_assignments', ['user_id'], unique=False)
    op.create_table('memberships',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_memberships_role_id_roles'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_memberships_team_id_teams'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_memberships_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memberships')),
    sa.UniqueConstraint('user_id', 'team_id', name='uq_memberships_user_id_team_id')
    )
    op.create_index(op.f('ix_memberships_team_id'), 'memberships', ['team_id'], unique=False)
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=False)
    op.create_table('proposal_events',
    sa.Column('proposal_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rule_evaluation_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_proposal_events_actor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], name=op.f('fk_proposal_events_proposal_id_proposals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_proposal_events'))
    )
    op.create_index('ix_proposal_events_proposal_created', 'proposal_events', ['proposal_id', 'created_at'], unique=False)
    op.create_table('role_permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_key', sa.String(length=80), nullable=False),
    sa.Column('scope', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['permission_key'], ['permissions.key'], name=op.f('fk_role_permissions_permission_key_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role_permissions')),
    sa.UniqueConstraint('role_id', 'permission_key', name='uq_role_permissions_role_id_permission_key')
    )
    op.create_index(op.f('ix_role_permissions_role_id'), 'role_permissions', ['role_id'], unique=False)
    op.create_table('rule_evaluations',
    sa.Column('decision_point', sa.String(length=60), nullable=False),
    sa.Column('rule_set_id', sa.UUID(), nullable=True),
    sa.Column('rule_set_version', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('entity_type', sa.String(length=60), nullable=True),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('facts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('matched_rule_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('trace', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('outcome', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('simulated', sa.Boolean(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_rule_evaluations_actor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rule_set_id'], ['rule_sets.id'], name=op.f('fk_rule_evaluations_rule_set_id_rule_sets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_rule_evaluations_team_id_teams'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rule_evaluations'))
    )
    op.create_index(op.f('ix_rule_evaluations_correlation_id'), 'rule_evaluations', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_rule_evaluations_decision_point'), 'rule_evaluations', ['decision_point'], unique=False)
    op.create_index('ix_rule_evaluations_dp_created', 'rule_evaluations', ['decision_point', 'created_at'], unique=False)
    op.create_index('ix_rule_evaluations_entity', 'rule_evaluations', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_rule_evaluations_simulated'), 'rule_evaluations', ['simulated'], unique=False)
    op.create_index(op.f('ix_rule_evaluations_team_id'), 'rule_evaluations', ['team_id'], unique=False)
    op.create_table('rule_set_versions',
    sa.Column('rule_set_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_rule_set_versions_author_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rule_set_id'], ['rule_sets.id'], name=op.f('fk_rule_set_versions_rule_set_id_rule_sets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rule_set_versions')),
    sa.UniqueConstraint('rule_set_id', 'version', name='uq_rule_set_versions_set_version')
    )
    op.create_table('rules',
    sa.Column('rule_set_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('actions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rule_set_id'], ['rule_sets.id'], name=op.f('fk_rules_rule_set_id_rule_sets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rules')),
    sa.UniqueConstraint('rule_set_id', 'position', name='uq_rules_set_position')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rules')
    op.drop_table('rule_set_versions')
    op.drop_index(op.f('ix_rule_evaluations_team_id'), table_name='rule_evaluations')
    op.drop_index(op.f('ix_rule_evaluations_simulated'), table_name='rule_evaluations')
    op.drop_index('ix_rule_evaluations_entity', table_name='rule_evaluations')
    op.drop_index('ix_rule_evaluations_dp_created', table_name='rule_evaluations')
    op.drop_index(op.f('ix_rule_evaluations_decision_point'), table_name='rule_evaluations')
    op.drop_index(op.f('ix_rule_evaluations_correlation_id'), table_name='rule_evaluations')
    op.drop_table('rule_evaluations')
    op.drop_index(op.f('ix_role_permissions_role_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index('ix_proposal_events_proposal_created', table_name='proposal_events')
    op.drop_table('proposal_events')
    op.drop_index(op.f('ix_memberships_user_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_team_id'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_label_assignments_user_id'), table_name='label_assignments')
    op.drop_index(op.f('ix_label_assignments_label_id'), table_name='label_assignments')
    op.drop_table('label_assignments')
    op.drop_table('assignment_policy_versions')
    op.drop_index('ix_rule_sets_dp_team', table_name='rule_sets')
    op.drop_table('rule_sets')
    op.drop_index('ix_roles_key', table_name='roles')
    op.drop_table('roles')
    op.drop_index('ix_proposals_team_status', table_name='proposals')
    op.drop_index(op.f('ix_proposals_team_id'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_status'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_external_ref'), table_name='proposals')
    op.drop_index('ix_proposals_bcd', table_name='proposals')
    op.drop_index(op.f('ix_proposals_assigned_to'), table_name='proposals')
    op.drop_index('ix_proposals_assigned_status', table_name='proposals')
    op.drop_table('proposals')
    op.drop_table('leave_settings')
    op.drop_index('ix_leave_requests_user_status', table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_user_id'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_team_id'), table_name='leave_requests')
    op.drop_index('ix_leave_requests_team_dates', table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_status'), table_name='leave_requests')
    op.drop_table('leave_requests')
    op.drop_index(op.f('ix_labels_kind'), table_name='labels')
    op.drop_index(op.f('ix_labels_key'), table_name='labels')
    op.drop_table('labels')
    op.drop_index(op.f('ix_holidays_start_date'), table_name='holidays')
    op.drop_table('holidays')
    op.drop_index(op.f('ix_audit_log_team_id'), table_name='audit_log')
    op.drop_index('ix_audit_log_entity', table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_correlation_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_actor_id'), table_name='audit_log')
    op.drop_index('ix_audit_log_actor_created', table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('ix_assignment_policies_team_active', table_name='assignment_policies')
    op.drop_table('assignment_policies')
    op.drop_index(op.f('ix_teams_slug'), table_name='teams')
    op.drop_table('teams')
    op.drop_index('ix_notifications_user_read', table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('leave_balances')
    op.drop_table('feature_flags')
    op.drop_index(op.f('ix_email_outbox_status'), table_name='email_outbox')
    op.drop_index(op.f('ix_email_outbox_correlation_id'), table_name='email_outbox')
    op.drop_table('email_outbox')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_azure_object_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_permissions_module'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index('ix_job_runs_task_started', table_name='job_runs')
    op.drop_index(op.f('ix_job_runs_task_name'), table_name='job_runs')
    op.drop_index(op.f('ix_job_runs_task_id'), table_name='job_runs')
    op.drop_index(op.f('ix_job_runs_status'), table_name='job_runs')
    op.drop_index(op.f('ix_job_runs_correlation_id'), table_name='job_runs')
    op.drop_table('job_runs')
    op.drop_table('connector_status')
    # ### end Alembic commands ###
